// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Category struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Todo struct {
	ID         int32     `json:"id"`
	CategoryID int32     `json:"category_id"`
	Title      string    `json:"title"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
	UserEmail  string    `json:"user_email"`
	Color      string    `json:"color"`
	Date       time.Time `json:"date"`
	IsPriority bool      `json:"is_priority"`
}

type User struct {
	ID             int32     `json:"id"`
	Name           string    `json:"name"`
	Address        string    `json:"address"`
	Pic            string    `json:"pic"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	HashedPassword string    `json:"hashed_password"`
	Email          string    `json:"email"`
}
